# 使用工具自动生成go struct
# goctl covert yaml --file=conf.yml --tags=json

# app 设置
app:
  name: "userExample"  # 服务名称
  env: "dev"                  # 运行环境，dev:开发环境，prod:生产环境，pre:预生产环境
  version: "v0.0.0"         # 版本
  hostIP: "127.0.0.1"     # 主机ip地址
  enableProfile: false       # 是否开启性能分析功能，true:开启，false:关闭
  enableMetrics: true   # 是否开启指标采集，true:开启，false:关闭
  enableLimit: false     # 是否开启限流，true:开启，false:关闭
  enableTracing: false    # 是否开启链路跟踪，true:开启，false:关闭
  enableRegistryDiscovery: true    # 是否开启注册与发现，true:开启，false:关闭


# http 设置
http:
  port: 8080            # 监听端口
  readTimeout: 3    # 读超时，单位(秒)
  writeTimeout: 90 # 写超时，单位(秒)，如果enableProfile为true，需要大于60s，pprof做profiling的默认值是60s


# grpc 服务设置
grpc:
  port: 9090          # 监听端口
  readTimeout: 3  # 读超时，单位(秒)
  writeTimeout: 3 # 写超时，单位(秒)


# logger 设置
logger:
  level: "info"             # 输出日志级别 debug, info, warn, error，默认是debug
  format: "console"     # 输出格式，console或json，默认是console
  isSave: false           # false:输出到终端，true:输出到文件，默认是false
  logFileConfig:         # isSave=true时有效
    filename: "out.log"    # 文件名称，默认值out.log
    maxSize: 20                     # 最大文件大小(MB)，默认值10MB
    maxBackups: 50                # 保留旧文件的最大个数，默认值100个
    maxAge: 15                      # 保留旧文件的最大天数，默认值30天
    isCompression: true          # 是否压缩/归档旧文件，默认值false


# mysql 设置
mysql:
  # dsn格式：<user>:<pass>@(127.0.0.1:3306)/<db>?[k=v& ......]
  dsn: "root:123456@(192.168.3.37:3306)/account?parseTime=true&loc=Local&charset=utf8,utf8mb4"
  enableLog: true                    # 是否开启打印所有日志
  slowThreshold: 0                  # 如果大于0，只打印时间大于阈值的日志，优先级比enableLog高，单位(毫秒)
  maxIdleConns: 3                 #设置空闲连接池中连接的最大数量
  maxOpenConns: 50              # 设置打开数据库连接的最大数量
  connMaxLifetime: 30           # 设置了连接可复用的最大时间，单位(分钟)


# redis 设置
redis:
  # dsn只适合redis6版本以上，默认用户为default，url格式 [user]:<pass>@]127.0.0.1:6379/[db]
  dsn: "default:123456@192.168.3.37:6379"
  # 适合各个版本redis
  addr: 127.0.0.1:6379
  password: "123456"
  dB: 0
  minIdleConn: 20
  dialTimeout: 30           # 链接超时，单位(秒)
  readTimeout: 500        # 读超时，单位(毫秒)
  writeTimeout: 500       # 写超时，单位(毫秒)
  poolSize: 100
  poolTimeout: 200        # 连接池超时，单位(秒)


# jaeger配置
jaeger:
  agentHost: "192.168.3.37"
  agentPort: "6831"
  samplingRate: 1.0     # 采样率，0~1之间，0表示禁止采样，大于等于1表示采样所有链路


# limit配置
rateLimiter:
  dimension: "path"   # 限流维度，支持path和ip两种，默认是path
  qpsLimit: 1000    # 持续每秒允许成功请求数，默认是500
  maxLimit: 2000  # 瞬时最大允许峰值，默认是1000，通常大于qpsLimit


# metrics配置
metrics:
  port: 9082


# etcd配置
etcd:
  addrs: ["192.168.3.37:2379"]
